development:
  adapter:  postgresql
  encoding: unicode
  database: test-volt_development

test:
  adapter:  postgresql
  encoding: unicode
  database: test-volt_test

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: test-volt_production
  pool:     5
  template: template0
