development:
  adapter:  postgresql
  encoding: unicode
  database: test-volt_development

test:
  adapter:  postgresql
  encoding: unicode
  database: test-volt_test

production:
  adapter:  postgresql
  encoding: unicode
  database: test-volt_production
  username: test-volt
  pool:     5
